version: '3.4'
networks:
  default:
    external:
      name: "dataclay-testing-network"
services:
  logicmoduleB:
    image: "dom-ci.bsc.es/bscdataclay/logicmodule:${JAVACLAY_IMAGE}"
    ports:
      - "22034:22034"
    command: "--debug"
    volumes:
      - type: bind
        source: /tmp/dataClay/functional-testing/storage/garbage-collection/machine-b
        target: /dataclay/storage
    environment:
      - LOGICMODULE_PORT_TCP=22034
      - LOGICMODULE_HOST=logicmoduleB
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      #- EXPOSED_IP_FOR_CLIENT=127.0.0.1
    deploy:
      resources:
        limits:
          memory: $LOGICMODULE_MAX_MEMORY
        reservations:
          memory: $LOGICMODULE_MIN_MEMORY
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
         
  dsjavaB:
    image: "dom-ci.bsc.es/bscdataclay/dsjava:${JAVACLAY_IMAGE}"
    ports:
      - "4127:4127"
    command: "--debug"
    depends_on:
      - logicmoduleB
    volumes:
      - type: bind
        source: /tmp/dataClay/functional-testing/storage/garbage-collection/machine-b
        target: /dataclay/storage
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=4127
      - LOGICMODULE_PORT_TCP=22034
      - LOGICMODULE_HOST=logicmoduleB
      - GLOBALGC_COLLECTOR_INITIAL_DELAY_HOURS=$GLOBALGC_COLLECTOR_INITIAL_DELAY_HOURS
      - GLOBALGC_MAX_TIME_QUARANTINE=$GLOBALGC_MAX_TIME_QUARANTINE
      - GLOBALGC_CHECK_REMOTE_PENDING=$GLOBALGC_CHECK_REMOTE_PENDING
      - GLOBALGC_PROCESS_COUNTINGS_INTERVAL=$GLOBALGC_PROCESS_COUNTINGS_INTERVAL
      - GLOBALGC_COLLECT_TIME_INTERVAL=$GLOBALGC_COLLECT_TIME_INTERVAL
      - GLOBALGC_MAX_OBJECTS_TO_COLLECT_ITERATION=$GLOBALGC_MAX_OBJECTS_TO_COLLECT_ITERATION
      - MEMMGMT_CHECK_TIME_INTERVAL=$MEMMGMT_CHECK_TIME_INTERVAL
      - MEMMGMT_PRESSURE_FRACTION=$MEMMGMT_PRESSURE_FRACTION
      - MEMMGMT_MIN_OBJECT_TIME=$MEMMGMT_MIN_OBJECT_TIME
    deploy:
      resources:
        limits:
          memory: $DSJAVA_MAX_MEMORY
        reservations:
          memory: $DSJAVA_MIN_MEMORY
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dspythonB:
    image: "dom-ci.bsc.es/bscdataclay/dspython:${PYCLAY_IMAGE}"
    ports:
      - "7867:7867"
    command: "--debug"
    depends_on:
      - logicmoduleB
      - dsjavaB
    volumes:
      - type: bind
        source: /tmp/dataClay/functional-testing/storage/garbage-collection/machine-b
        target: /dataclay/storage
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_PYTHON_PORT_TCP=7867
      - LOGICMODULE_PORT_TCP=22034
      - LOGICMODULE_HOST=logicmoduleB
      - MEMMGMT_CHECK_TIME_INTERVAL=$MEMMGMT_CHECK_TIME_INTERVAL
      - MEMMGMT_PRESSURE_FRACTION=$MEMMGMT_PRESSURE_FRACTION
      - MEMMGMT_MIN_OBJECT_TIME=$MEMMGMT_MIN_OBJECT_TIME
      #- LOGLEVEL=TRACE
    deploy:
      resources:
        limits:
          memory: $DSPYTHON_MAX_MEMORY
        reservations:
          memory: $DSPYTHON_MIN_MEMORY
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]