version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
environment:
  MN_SALT:
    secure: A2CVXopXaMJuIZw+vkdiklA4nLKgFmjW9W3PpofFBi1elXHhnPaoHbdOv6Rk1NHP04O7y8D7l21XzmPgYtZF8g==
  MN_SECRET:
    secure: fOYbgYSg0A2yudFL4mi8glRpB/VlAdbf0Genq44vLws=
  DOCKER_USERNAME:
    secure: d9s0OSEPlE156nPrhrsNnA==
  DOCKER_PASSWORD:
    secure: TO42yeTsoNEkuoRQ9ES7MQ==
  DOCKER_CLI_EXPERIMENTAL: enabled
  matrix:
    # Group 1
    - TEST_ENV: "01_*" jdk8 linux/amd64 normal
    - TEST_ENV: "01_*" jdk8 linux/amd64 slim
    - TEST_ENV: "01_*" jdk8 linux/arm64 normal
    - TEST_ENV: "01_*" jdk8 linux/arm64 slim
    - TEST_ENV: "01_*" jdk8 linux/arm/v7 normal
    - TEST_ENV: "01_*" jdk8 linux/arm/v7 slim
    - TEST_ENV: "01_*" jdk11 linux/amd64 normal
    - TEST_ENV: "01_*" jdk11 linux/amd64 slim
    - TEST_ENV: "01_*" jdk11 linux/amd64 alpine
    - TEST_ENV: "01_*" jdk11 linux/arm64 normal
    - TEST_ENV: "01_*" jdk11 linux/arm64 slim
    - TEST_ENV: "01_*" jdk11 linux/arm64 alpine
    - TEST_ENV: "01_*" jdk11 linux/arm/v7 normal
    - TEST_ENV: "01_*" jdk11 linux/arm/v7 slim
    # Group 2
    - TEST_ENV: "02_*" jdk8 linux/amd64 normal
    - TEST_ENV: "02_*" jdk8 linux/amd64 slim
    - TEST_ENV: "02_*" jdk8 linux/arm64 normal
    - TEST_ENV: "02_*" jdk8 linux/arm64 slim
    - TEST_ENV: "02_*" jdk8 linux/arm/v7 normal
    - TEST_ENV: "02_*" jdk8 linux/arm/v7 slim
    - TEST_ENV: "02_*" jdk11 linux/amd64 normal
    - TEST_ENV: "02_*" jdk11 linux/amd64 slim
    - TEST_ENV: "02_*" jdk11 linux/amd64 alpine
    - TEST_ENV: "02_*" jdk11 linux/arm64 normal
    - TEST_ENV: "02_*" jdk11 linux/arm64 slim
    - TEST_ENV: "02_*" jdk11 linux/arm64 alpine
    - TEST_ENV: "02_*" jdk11 linux/arm/v7 normal
    - TEST_ENV: "02_*" jdk11 linux/arm/v7 slim
    # Group 3
    - TEST_ENV: "03_*" jdk8 linux/amd64 normal
    - TEST_ENV: "03_*" jdk8 linux/amd64 slim
    - TEST_ENV: "03_*" jdk8 linux/arm64 normal
    - TEST_ENV: "03_*" jdk8 linux/arm64 slim
    - TEST_ENV: "03_*" jdk8 linux/arm/v7 normal
    - TEST_ENV: "03_*" jdk8 linux/arm/v7 slim
    - TEST_ENV: "03_*" jdk11 linux/amd64 normal
    - TEST_ENV: "03_*" jdk11 linux/amd64 slim
    - TEST_ENV: "03_*" jdk11 linux/amd64 alpine
    - TEST_ENV: "03_*" jdk11 linux/arm64 normal
    - TEST_ENV: "03_*" jdk11 linux/arm64 slim
    - TEST_ENV: "03_*" jdk11 linux/arm64 alpine
    - TEST_ENV: "03_*" jdk11 linux/arm/v7 normal
    - TEST_ENV: "03_*" jdk11 linux/arm/v7 slim
    # Group 4
    - TEST_ENV: "04_*" jdk8 linux/amd64 normal
    - TEST_ENV: "04_*" jdk8 linux/amd64 slim
    - TEST_ENV: "04_*" jdk8 linux/arm64 normal
    - TEST_ENV: "04_*" jdk8 linux/arm64 slim
    - TEST_ENV: "04_*" jdk8 linux/arm/v7 normal
    - TEST_ENV: "04_*" jdk8 linux/arm/v7 slim
    - TEST_ENV: "04_*" jdk11 linux/amd64 normal
    - TEST_ENV: "04_*" jdk11 linux/amd64 slim
    - TEST_ENV: "04_*" jdk11 linux/amd64 alpine
    - TEST_ENV: "04_*" jdk11 linux/arm64 normal
    - TEST_ENV: "04_*" jdk11 linux/arm64 slim
    - TEST_ENV: "04_*" jdk11 linux/arm64 alpine
    - TEST_ENV: "04_*" jdk11 linux/arm/v7 normal
    - TEST_ENV: "04_*" jdk11 linux/arm/v7 slim
build_script:
  - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
      -v ${HOME}/.docker/config.json:/root/.docker/config.json:ro \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e MN_SALT=$MN_SALT \
      -e MN_SECRET=$MN_SECRET \
      -w=$APPVEYOR_BUILD_FOLDER \
      bscdataclay/continuous-integration:testing \
      ./test_all_features_in_env.sh $TEST_ENV
    EXIT_CODE=$?
    docker logout
    exit $EXIT_CODE
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true