version: functesting.deploy.build{build}
build_cloud: bsccsdomci01
branches:
  only:
    - main
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
deploy_script: ./deploy.sh --plain --deploy-base
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true