version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
environment:
  MN_SALT:
    secure: y0lD3CmSDZQx7zsNkyqUQyFtiV2eoewZ94bxSk9yoUrc6Mfgto18k7hzAitfVxs124Pai3GGvBpDZppuXikFPQ==
  MN_SECRET:
    secure: +ZRoLZnCowoJI/RvYao/XzgDz4usFDcZRX5aRoTBHUY=
  DOCKER_USERNAME:
    secure: BjCQHIN21F+sOx1mQICY5Q==
  DOCKER_PASSWORD:
    secure: 4tDbnFmVNXL6+VAwzvb61w==
  DOCKER_CLI_EXPERIMENTAL: enabled
  EXEC_ENV: py37
  TESTING_ARCH: linux/arm/v7
  matrix:
    # Group 1
    - TEST_ENV: normal 01_*
    - TEST_ENV: slim 01_*
    - TEST_ENV: alpine 01_*
    # Group 2
    - TEST_ENV: normal 02_*
    - TEST_ENV: slim 02_*
    - TEST_ENV: alpine 02_*
    # Group 3
    - TEST_ENV: normal 03_*
    - TEST_ENV: slim 03_*
    - TEST_ENV: alpine 03_*
    # Group 4
    - TEST_ENV: normal 04_*
    - TEST_ENV: slim 04_*
    - TEST_ENV: alpine 04_*
install:
  - |
    sudo apt-get update
    sudo apt-get install -y binfmt-support qemu qemu-user-static jq
    echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
    sudo service docker restart
build_script:
  - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
      -v ${HOME}/.docker/config.json:/root/.docker/config.json:ro \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e MN_SALT=$MN_SALT \
      -e MN_SECRET=$MN_SECRET \
      -w=$APPVEYOR_BUILD_FOLDER \
      bscdataclay/continuous-integration:testing \
      ./test_all_features_in_env.sh $TESTING_ARCH $EXEC_ENV $TEST_ENV
    EXIT_CODE=$?
    docker logout
    exit $EXIT_CODE
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true