version: 2.6.dev.build{build}
build_cloud: bsccsdomci01
branches:
  only:
    - main
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
platform:
  - linux/amd64
  - linux/arm64
  - linux/arm/v7
configuration:
  - normal
  - slim
  - alpine
  - arm32
environment:
  matrix:
    - FEATURE: makepersistent
    - FEATURE: getbyalias
    - FEATURE: dynamicity
    - FEATURE: new-replica
    - FEATURE: new-replica
    - FEATURE: new-version-consolidate
    - FEATURE: federation
build_script:
  - |
    echo "Platform = $PLATFORM"
    echo "Image type = $CONFIGURATION"
    echo "Feature = $FEATURE"
    docker run --rm -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -w=$APPVEYOR_BUILD_FOLDER \
          dom-ci.bsc.es/bscdataclay/continuous-integration:testing \
          ./test_features.sh --tests "${FEATURE}.feature" --platforms "$PLATFORM" --image-types "$CONFIGURATION" --environments-with-prefix py
    EXIT_CODE=$?
    mkdir -p ~/allure-results/$APPVEYOR_BUILD_ID/
    cp -r ./allure-results/* ~/allure-results/$APPVEYOR_BUILD_ID/
    exit $EXIT_CODE
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true