version: pyclay.functesting.amd64.build{build}
build_cloud: bsccsdomci01
branches:
  only:
    - main
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1
### MAXIMUM allowed combinations are 100, so images x platforms x configurations x environments <= 100 ####
image:
  - normal
  - slim
  - alpine
platform:
  - linux/amd64
configuration:
  - py36
  - py37
  - py38
environment:
  matrix:
    - FEATURE: makepersistent
    - FEATURE: getbyalias
    - FEATURE: dynamicity
    - FEATURE: new-replica
    - FEATURE: new-version-consolidate
    - FEATURE: federation
    - FEATURE: garbage-collection
    - FEATURE: object-store
build_script:
  - |
    echo "Image = $APPVEYOR_BUILD_WORKER_IMAGE"
    echo "Platform = $PLATFORM"
    echo "Environment = $CONFIGURATION"
    echo "Feature = $FEATURE"
    ./test_features.sh --tests "${FEATURE}.feature" --platforms "$PLATFORM" \
          --image-types "$APPVEYOR_BUILD_WORKER_IMAGE" --environments "$CONFIGURATION"
    EXIT_CODE=$?
    mkdir -p ~/allure-results/$APPVEYOR_BUILD_ID/
    cp -r ./allure-results/* ~/allure-results/$APPVEYOR_BUILD_ID/
    exit $EXIT_CODE
notifications:
  - provider: Email
    to:
      - support-dataclay@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true