name: Python Functional Tests
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * mon'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        platform: [linux/amd64]
        image: [normal]
        python-version: [py36, py38]
        feature: [makepersistent, getbyalias, dynamicity, new-replica, new-version-consolidate, federation, garbage-collection, object-store]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./test_features.sh --tests "${{ matrix.feature }}.feature" --platforms ${{ matrix.platform }} \
          --image-types ${{ matrix.image }} --environments ${{ matrix.python-version }}
