version: '3.4'
networks:
  default:
    external:
      name: "dataclay-testing-network"
services:
  logicmoduleC:
    image: "dom-ci.bsc.es/bscdataclay/logicmodule:${JAVACLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    ports:
      - "42034:42034"
    command: "--debug"
    environment:
      - LOGICMODULE_PORT_TCP=42034
      - LOGICMODULE_HOST=logicmoduleC
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      #- EXPOSED_IP_FOR_CLIENT=127.0.0.1
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
         
  dsjavaC:
    image: "dom-ci.bsc.es/bscdataclay/dsjava:${JAVACLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    ports:
      - "14127:14127"
    command: "--debug"
    depends_on:
      - logicmoduleC
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=14127
      - LOGICMODULE_PORT_TCP=42034
      - LOGICMODULE_HOST=logicmoduleC
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dspythonC:
    image: "dom-ci.bsc.es/bscdataclay/dspython:${PYCLAY_IMAGE}"
    platform: ${IMAGE_PLATFORM}
    ports:
      - "17867:17867"
    command: "--debug"
    depends_on:
      - logicmoduleC
      - dsjavaC
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_PYTHON_PORT_TCP=17867
      - LOGICMODULE_PORT_TCP=42034
      - LOGICMODULE_HOST=logicmoduleC
    stop_grace_period: 5m
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
